name: sonar-scanner

on: [push, pull_request]

jobs:
  SonarScanner:
    if: github.repository == 'zeegin/OpenSubsystemsLibrary'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup SonarQube scanner
      uses: warchant/setup-sonar-scanner@v1
    - name: Run SonarQube on push
      if: github.event_name == 'push'
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.branch.name=${{ github.ref }}
    - name: Run SonarQube on pull request
      if: github.event_name == 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.repository.full_name
      run: sonar-scanner
        -X
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.branch.name=${{ github.ref }}
        -Dsonar.branch.target=${{ github.base_ref }}
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        -Dsonar.pullrequest.branch=${{ github.ref }}
        -Dsonar.pullrequest.base=${{ github.base_ref }}
