name: sonar-scanner

on:
  pull_request:
    branches:
    - master 
  push: 
    branches: 
    - master  

jobs:
  SonarScanner:
    if: github.repository == 'zeegin/OpenSubsystemsLibrary'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run SonarQube
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONARCLOUD_URL: https://sonar.openbsl.ru
